name: Bug Report
description: File a bug report.
title: "[Version] Bug:"
assignees:
  - Edouard127
body:
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to report a bug. Please fill out the information below to the best of your ability.
        Before submitting your issue, please check to see if it has already been reported.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what happened
      value: "
      Ex: 
      - I got a deadlock on the goroutine that handles the connection to the server.
      - invalid memory address or nil pointer dereference
      - The server crashed for no reason
      "
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      placeholder: Tell us what should have happened
      value: "x"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please copy the entire crash trace and thread dumps (if possible).