// Package openapi_spec Code generated by swaggo/swag. DO NOT EDIT
package openapi_spec

import "github.com/swaggo/swag"

const docTemplatev1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Lambda Discord",
            "url": "https://discord.gg/J23U4YEaAr"
        },
        "license": {
            "name": "GNU General Public License v3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/party/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new party",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Party"
                ],
                "summary": "Create a new party",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Party"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.Party"
                        }
                    }
                }
            }
        },
        "/party/join": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Join a party",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Party"
                ],
                "summary": "Join a party",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Party"
                        }
                    }
                }
            }
        },
        "/party/login": {
            "post": {
                "description": "Login to the server using a Discord identify token, a Minecraft username and a Mojang session hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Party"
                ],
                "summary": "Login to the server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discord identify token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Minecraft username",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mojang session hash",
                        "name": "hash",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Authentication"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Authentication": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "The access token to use for the API\nexample: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
                    "type": "string"
                },
                "expires_in": {
                    "description": "The duration of the token (in seconds).\nexample: 3600",
                    "type": "integer"
                },
                "message": {
                    "description": "The message to display to the user.\nexample: Successfully logged in.",
                    "type": "string"
                },
                "token_type": {
                    "description": "The type of the token.\nexample: Bearer",
                    "type": "string"
                }
            }
        },
        "models.DiscordUser": {
            "type": "object",
            "properties": {
                "global_name": {
                    "description": "The user's name.\nexample: john.doe",
                    "type": "string"
                },
                "id": {
                    "description": "The user's ID.\nexample: 1234567890",
                    "type": "integer"
                },
                "username": {
                    "description": "The user's username.\nexample: John Doe",
                    "type": "string"
                }
            }
        },
        "models.MinecraftPlayer": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "The player's UUID.\nexample: 069a79f4-44e9-4726-a5be-fca90e38aaf5",
                    "type": "string"
                },
                "name": {
                    "description": "The player's name.\nexample: Notch",
                    "type": "string"
                }
            }
        },
        "models.Party": {
            "type": "object",
            "properties": {
                "creation": {
                    "description": "The creation date of the party.\nexample: 2021-10-10T12:00:00Z",
                    "type": "string"
                },
                "id": {
                    "description": "The ID of the party.\nIt is a random string of 69 characters.",
                    "type": "string"
                },
                "players": {
                    "description": "The list of players in the party.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Player"
                    }
                }
            }
        },
        "models.Player": {
            "type": "object",
            "properties": {
                "discord": {
                    "description": "The Discord user.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DiscordUser"
                        }
                    ]
                },
                "player": {
                    "description": "The Minecraft player.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MinecraftPlayer"
                        }
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfov1 holds exported Swagger Info so clients can modify it
var SwaggerInfov1 = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Lambda RPC API",
	Description:      "This is the API for the Lambda Discord RPC handler",
	InfoInstanceName: "v1",
	SwaggerTemplate:  docTemplatev1,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov1.InstanceName(), SwaggerInfov1)
}
