// Package openapi_spec Code generated by swaggo/swag. DO NOT EDIT
package openapi_spec

import "github.com/swaggo/swag"

const docTemplatev1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Lambda Discord",
            "url": "https://discord.gg/J23U4YEaAr"
        },
        "license": {
            "name": "GNU General Public License v3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/party/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new party",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Party"
                ],
                "summary": "Create a new party",
                "parameters": [
                    {
                        "description": "Settings",
                        "name": "Settings",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.Settings"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Party"
                        }
                    }
                }
            }
        },
        "/party/join": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Join a party",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Party"
                ],
                "summary": "Join a party",
                "parameters": [
                    {
                        "description": "Party ID",
                        "name": "ID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/response.Party"
                        }
                    }
                }
            }
        },
        "/party/login": {
            "post": {
                "description": "Login to the server using a Discord identify token, a Minecraft username and a Mojang session hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Party"
                ],
                "summary": "Login to the server",
                "parameters": [
                    {
                        "description": "Authentication",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Authentication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Authentication"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.Authentication": {
            "type": "object",
            "required": [
                "hash",
                "token",
                "username"
            ],
            "properties": {
                "hash": {
                    "description": "The player's Mojang session hash.\nexample: 069a79f444e94726a5befca90e38aaf5",
                    "type": "string"
                },
                "token": {
                    "description": "The player's Discord token.\nexample: OTk1MTU1NzcyMzYxMTQ2NDM4.AAAAAA.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
                    "type": "string"
                },
                "username": {
                    "description": "The player's username.\nexample: Notch",
                    "type": "string"
                }
            }
        },
        "request.Settings": {
            "type": "object",
            "required": [
                "listed",
                "max_players",
                "public"
            ],
            "properties": {
                "listed": {
                    "description": "Whether the party can be listed or not.\nexample: true",
                    "type": "boolean"
                },
                "max_players": {
                    "description": "The maximum number of players in the party.\nexample: 10",
                    "type": "integer"
                },
                "public": {
                    "description": "Whether the party is public or not.\nIf false can only be joined by invite.\nexample: true",
                    "type": "boolean"
                }
            }
        },
        "response.Authentication": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "The access token to use for the API\nexample: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
                    "type": "string"
                },
                "expires_in": {
                    "description": "The duration of the token (in seconds).\nexample: 3600",
                    "type": "integer"
                },
                "token_type": {
                    "description": "The type of the token.\nexample: Bearer",
                    "type": "string"
                }
            }
        },
        "response.Party": {
            "type": "object",
            "properties": {
                "creation": {
                    "description": "The creation date of the party.\nexample: 2021-10-10T12:00:00Z",
                    "type": "string"
                },
                "id": {
                    "description": "The ID of the party.\nIt is a random string of 30 characters.",
                    "type": "string"
                },
                "join_secret": {
                    "description": "The join secret of the party.\nIt is a random string of 100 characters.",
                    "type": "string"
                },
                "leader": {
                    "description": "The leader of the party.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Player"
                        }
                    ]
                },
                "players": {
                    "description": "The list of players in the party.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Player"
                    }
                },
                "settings": {
                    "description": "The settings of the party.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Settings"
                        }
                    ]
                }
            }
        },
        "response.Player": {
            "type": "object",
            "properties": {
                "discord_id": {
                    "description": "The player's Discord ID.\nexample: \"385441179069579265\"",
                    "type": "string"
                },
                "id": {
                    "description": "The player's UUID.\nexample: 069a79f4-44e9-4726-a5be-fca90e38aaf5",
                    "type": "string"
                },
                "name": {
                    "description": "The player's name.\nexample: Notch",
                    "type": "string"
                }
            }
        },
        "response.Settings": {
            "type": "object",
            "required": [
                "listed",
                "max_players",
                "public"
            ],
            "properties": {
                "listed": {
                    "description": "Whether the party can be listed or not.\nexample: true",
                    "type": "boolean"
                },
                "max_players": {
                    "description": "The maximum number of players in the party.\nexample: 10",
                    "type": "integer"
                },
                "public": {
                    "description": "Whether the party is public or not.\nIf false can only be joined by invite.\nexample: true",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfov1 holds exported Swagger Info so clients can modify it
var SwaggerInfov1 = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Lambda RPC API",
	Description:      "This is the API for the Lambda Discord RPC handler",
	InfoInstanceName: "v1",
	SwaggerTemplate:  docTemplatev1,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov1.InstanceName(), SwaggerInfov1)
}
